name: easy_scooter
description: "A new Flutter project."
publish_to: "none"
version: 1.3.1+1

fonts:
  - family: AlibabaSans
    fonts:
      - asset: assets/fonts/AlibabaSans-Medium.otf
      - asset: assets/fonts/AlibabaSans-Bold.otf
        weight: 700
      - asset: assets/fonts/AlibabaSans-Italic.otf
        style: italic
environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.2
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  dio: ^5.8.0+1
  provider: ^6.1.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pretty_dio_logger: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # 或者你可以包含整个目录
    # - assets/images/
