version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/rental_platform
      - SECRET_KEY=${SECRET_KEY:-25時ナイトコードで}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - PROJECT_NAME=${PROJECT_NAME:-"Electric Scooter Rental Platform"}
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rental_platform
    ports:
      - "5432:5432"

volumes:
  postgres_data: