"""migration message

Revision ID: 13f72349c41f
Revises: c95c42e165bd
Create Date: 2025-04-18 18:57:19.722990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f72349c41f'
down_revision: Union[str, None] = 'c95c42e165bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scooter_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('price_per_minute', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model', name='uq_scooter_model')
    )
    op.create_index(op.f('ix_scooter_prices_id'), 'scooter_prices', ['id'], unique=False)
    op.create_index(op.f('ix_scooter_prices_model'), 'scooter_prices', ['model'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scooter_prices_model'), table_name='scooter_prices')
    op.drop_index(op.f('ix_scooter_prices_id'), table_name='scooter_prices')
    op.drop_table('scooter_prices')
    # ### end Alembic commands ###
