"""migration message

Revision ID: d8cdb02ff467
Revises: 13f72349c41f
Create Date: 2025-04-18 19:02:52.112309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8cdb02ff467'
down_revision: Union[str, None] = '13f72349c41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scooter_prices', sa.Column('price_per_hour', sa.Float(), nullable=False))
    op.drop_column('scooter_prices', 'price_per_minute')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scooter_prices', sa.Column('price_per_minute', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('scooter_prices', 'price_per_hour')
    # ### end Alembic commands ###
